  - alias: 'Start HomeKit'
    trigger:
      - platform: event
        event_type: zwave.network_ready
      - platform: event
        event_type: zwave.network_complete
    action:
      - service: homekit.start
  
  #Arlo
  - alias: Enable Arlo upon HA start'
    initial_state: 'on'
    trigger:
      platform: homeassistant
      event: start
    action:
      service: camera.enable_motion_detection
      entity_id: camera.arlo_frontdoor