- platform: template
  sensors:
          aeotec_multisensor_motion:
                  value_template: "{%if states.sensor.aeotec_multisensor_6_burglar_3.state == '8' %}motion detected{% elif states.sensor.aeotec_multisensor_6_burglar_3.state == '3' %}tamper{% elif states.sensor.aeotec_multisensor_6_burglar_3.state == '0' %}standby{% endif %}"
                  friendly_name: "Aeotec Motion"
