

#Weather forecast
- platform: yr
  name: YR
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - windDirection
    - humidity

- platform: systemmonitor

- platform: time_date
  display_options:
    - 'time'

#uptime sensor
- platform: uptime
  name: Time Online
  unit_of_measurement: hours
